export const Routes = {
  SPLASH: '/',
  WALKTHROUGH: '/(auth)/walkthrough',
  LOGIN: '/(auth)/login',
  FORGOT_PASSWORD: '/(auth)/forgot-password',
  FORGOT_PASSWORD_OTP: '/(auth)/forgot-password/otp',
  FORGOT_PASSWORD_NEW: '/(auth)/forgot-password/new-password',
  CREATE_ACCOUNT_TYPE: '/(auth)/create-account-type',
  CREATE_ACCOUNT_WORKPLACE: '/(auth)/create-account-workplace',
  CREATE_ACCOUNT_PROFILE: '/(auth)/create-account-profile',
  REGISTER: '/(auth)/register',
  HOME: '/(tabs)/home',
  PROFILE: '/(tabs)/profile',
  STATISTICS: '/statistics',
  NETWORK: '/network',
  SETTINGS: '/settings',
  SETTINGS_PERSONAL: '/settings/personal-info',
  SETTINGS_NOTIFICATIONS: '/settings/notifications',
  SETTINGS_MUSIC: '/settings/music',
  SETTINGS_SECURITY: '/settings/security',
  SETTINGS_HELP: '/settings/help',
  SETTINGS_ABOUT: '/settings/about',
  PREMIUM: '/premium',
  PREMIUM_COMPARE: '/premium/compare',
  PREMIUM_PLANS: '/premium/plans',
  PREMIUM_PAYMENT: '/premium/payment',
  PREMIUM_SUCCESS: '/premium/success',
} as const;
